plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

base {
	archivesName = 'world-transfer-fabric'
}

loom {
	splitEnvironmentSourceSets()
	mods {
		worldtransfer {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

sourceSets.main.java.srcDirs = ['src/main/java']
sourceSets.main.resources.srcDirs = ['src/main/resources']
sourceSets.client.java.srcDirs = ['src/client/java']

dependencies {
	minecraft "com.mojang:minecraft:${minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
	implementation project(':common')
}

tasks.named('jar') {
	dependsOn project(':common').tasks.named('classes')
	from project(':common').sourceSets.main.output
}

processResources {
	inputs.property 'version', project.version
	filesMatching('fabric.mod.json') {
		expand 'version': project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 25
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

publishing {
	publications {
		mavenJava(MavenPublication) {
			from components.java
		}
	}
}