org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.java.home=C:/Program Files/Eclipse Adoptium/jdk-25.0.4.101-hotspot

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

mod_version=0.5.0+mc.26.3
group=com.worldtransfer
fabric_api_version=0.160.5+26.3
moddev_version=2.0.147
neoforge_version=26.3.0.7-beta
neoform_version=26.3-1
